### ISSUE TITLE
Practica_7

### ISSUE THREAD

**Issue by 22620188Oliverio** [SistemasTecTlaxiaco/actividad-7-practica-de-entrevista-equpio-lor-xd#1]
[ENTREVISTA_REPORTE.pdf](https://github.com/user-attachments/files/17564709/ENTREVISTA_REPORTE.pdf)

**Comment by Reyesjessica** [comment]
27 ,le faltaron las repuesta de los usuarios(entrevistados) y faltaron más imágenes

**Comment by josealfredo79** [comment]
bien hecho y revisado..
